Fix freezing for Windows
Before, freezing in Windows ended with the error
    ValueError: Unexpected status '404 NOT FOUND' on URL /v1/css\bootstrap.css
due to mixing / and \.
Fix this using PurePosixPath